-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 21, 2022 at 06:39 AM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `quiz`

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE `questions` (
  `sno` int(4) DEFAULT NULL,
  `question` varchar(1500) DEFAULT NULL,
  `op1` varchar(800) DEFAULT NULL,
  `op2` varchar(800) DEFAULT NULL,
  `op3` varchar(800) DEFAULT NULL,
  `op4` varchar(800) DEFAULT NULL,
  `ans` varchar(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`sno`, `question`, `op1`, `op2`, `op3`, `op4`, `ans`) VALUES
(69, 'Which of the following statements about the null pointer is correct?', 'The null pointer is similar to an uninitialized pointer', 'You can declare a null pointer as char* p = (char*)0', 'The NULL macro is defined only in the stdio.h header', 'The sizeof( NULL) operation would return the value 1', 'B'),
(67, 'Which of the following statements about functions is false?', 'The main() function can be called recursively', 'Functions cannot return more than one value at a time', 'A function can have multiple return statements with different return values', 'The maximum number of arguments a function can take is 128', 'D'),
(20, 'Which of the following return-type cannot be used for a function in C?', 'char*', 'struct', 'void', 'None of the mentioned', 'D'),
(1, 'Which of the following language is the predecessor to C Programming Language?', 'A', 'B', 'BCPL', 'C++', 'C'),
(19, 'Which of the following is not possible statically in C language?', 'Jagged Array', 'Array', ' 2D Array', 'Multidimensional Array', 'A'),
(9, 'Which of the following is not a valid C variable name?', 'int number;', 'float rate', 'int variable_count', 'int $main;', 'D'),
(35, 'Which of the following is executed by Preprocess?', '#include&lt;stdio.h&gt;', 'return 0', 'void main(int argc , char ** argv)', 'None of the mentioned', 'A'),
(6, 'Which of the following is a ternary operator?', '?:', '*', 'sizeof', '^', 'A'),
(10, 'Which of the following cannot be a variable name in C?', 'volatile', '1', 'friend', 'export', 'A'),
(17, 'Which of following is not accepted in C?', 'static a = 10; //static as', 'static int func (int); //parameter as static', 'static static int a; //a static variable prefixed with static', 'all of the mentioned', 'C'),
(15, 'Which library function can convert an integer/long to a string?', 'Itoa()', 'ultoa()', 'sprintf()', 'None of the mentioned', 'A'),
(16, 'Which is valid C expression?', 'int my_num = 100,000;', 'int my_num = 100000', 'int my num = 1000', 'int $my_num = 10000;', 'B'),
(26, 'What will this program print?\n\n<br>\r\n&nbsp; &nbsp;main()\n\n<br>\r\n&nbsp; &nbsp;{<br>\r\n&nbsp; &nbsp;\n  int i = 2;\n\n<br>\r\n&nbsp; &nbsp;\n  { <br>\r\n&nbsp; &nbsp; \n    int i = 4, j = 5; \n\n<br>\r\n&nbsp; &nbsp;\n     printf(\"%d %d\", i, j);\n\n<br>\r\n&nbsp; &nbsp;\n     \n  printf(\"%d %d\", i, j); \n\n<br>\r\n&nbsp; &nbsp; \n}  \n\n<br>\r\n&nbsp; &nbsp;} ', '4525', '2525', '4545', 'None of the mentioned', 'C'),
(27, 'What will the output after execution of the following statements?\n\n\n\n<br>\r\n&nbsp; &nbsp;void main() \n\n<br>\r\n&nbsp; &nbsp; \n{  \n<br>\r\n&nbsp; &nbsp;\n  int i = 065, j = 65;\n\n<br>\r\n&nbsp; &nbsp;  \n  printf (\"%d %d\", i, j); \n\n<br>\r\n&nbsp; &nbsp; \n}  ', '065 65', '53 65', '65  65   ', 'syntax error', 'B'),
(28, 'What will the output after execution of the following statements?\n\n<br>\r\n&nbsp; &nbsp;main() \n\n<br>\r\n&nbsp; &nbsp; \n{ \n\n<br>\r\n&nbsp; &nbsp; \n  printf (\"ab\");\n\n<br>\r\n&nbsp; &nbsp;  \n  printf (\"si\");\n\n<br>\r\n&nbsp; &nbsp;  \n  printf (\"ha\"); \n\n<br>\r\n&nbsp; &nbsp; \n}  ', 'absiha', 'asiha', 'haasi', 'hai', 'D'),
(56,  'How to stop Name Mangling(Creating unique names) in C++?<br>', 'It is not possible', 'It is possible only with C code', 'By using extern \"C\" keyword', 'By Converting C++ code to C', 'C'),
(71, 'What will be the output of the following code snippet?\n\n<br>\r\n&nbsp; &nbsp;#include &lt;stdio.h&gt;\n\n<br>\r\n&nbsp; &nbsp;\n#include&lt;string.h&gt;\nvoid solve()\n\n<br>\r\n&nbsp; &nbsp; {\n   \n\n<br>\r\n&nbsp; &nbsp; char s[] = \"Hello\";\n\n<br>\r\n&nbsp; &nbsp;\n    printf(\"%s \", s);\n\n<br>\r\n&nbsp; &nbsp;\n    char t[40];\n\n<br>\r\n&nbsp; &nbsp;\n    strcpy(t, s);\n\n<br>\r\n&nbsp; &nbsp;\n    printf(\"%s\", t);\n\n<br>\r\n&nbsp; &nbsp;\n}\n\n<br>\r\n&nbsp; &nbsp;\nint main() {\n \n\n<br>\r\n&nbsp; &nbsp;   solve();\n\n<br>\r\n&nbsp; &nbsp; return 0;\n\n<br>\r\n&nbsp; &nbsp;\n}', 'Hello Hello', 'Hello', 'Compile error', 'None of the mentioned', 'A'),
(22, 'What will be the output of the following C code? \n\n<br>\r\n&nbsp; &nbsp;(Initial values: x= 7, y = 8) \n\n<br>\r\n&nbsp; &nbsp;void main()\n    {\n\n<br>\r\n&nbsp; &nbsp;       float x;\n   \n\n<br>\r\n&nbsp; &nbsp;     int y;\n   \n\n<br>\r\n&nbsp; &nbsp;     printf(\"enter two numbers \\n\", x);\n\n<br>\r\n&nbsp; &nbsp;\n        scanf(\"%f %f\", &x, &y);\n\n<br>\r\n&nbsp; &nbsp;\n        printf(\"%f, %d\", x, y);\n\n<br>\r\n&nbsp; &nbsp;\n    }', '7.000000,7', 'Run time erroe', '7.00000,junk', 'varies', 'A'),
(53, 'What will be the output of the following C code?\n<br>\r\n&nbsp; &nbsp; #include &lt;stdio.h&gt;\n   \n\n<br>\r\n&nbsp; &nbsp; int main()\n \n\n<br>\r\n&nbsp; &nbsp;   {\n\n\n<br>\r\n&nbsp; &nbsp;        for (int k = 0; k &lt; 10; k++);\n\n<br>\r\n&nbsp; &nbsp;\n            return 0\n\n<br>\r\n&nbsp; &nbsp;\n    }', 'yes', 'no', 'error', 'Depends on the C standard implemented by compilers', 'C'),
(52, 'What will be the output of the following C code?\n\n<br>\r\n&nbsp; &nbsp;    #include &lt;stdio.h&gt;\n\n<br>\r\n&nbsp; &nbsp;\n    int const print()\n\n\n<br>\r\n&nbsp; &nbsp;    {\n \n\n<br>\r\n&nbsp; &nbsp;       printf(\"URCE.com\");\n\n<br>\r\n&nbsp; &nbsp;\n        return 0;\n \n\n<br>\r\n&nbsp; &nbsp;   }\n  \n\n<br>\r\n&nbsp; &nbsp;  void main()\n    {\n  \n\n<br>\r\n&nbsp; &nbsp;        print();\n\n\n<br>\r\n&nbsp; &nbsp;      }', 'Error because function name cannot be preceded by const', ' URCE.com', ' URCE.com is printed infinite times', 'Blank screen, no output', 'B'),
(54, 'What will be the output of the following C code considering the size of a short int is 2, char is 1 and int is 4 bytes?\n\n<br>\r\n&nbsp; &nbsp; #include &lt;stdio.h&gt;\n \n\n<br>\r\n&nbsp; &nbsp;   int main()\n  \n\n<br>\r\n&nbsp; &nbsp;  {\n\n\n<br>\r\n&nbsp; &nbsp;        short int i = 20;\n  \n\n<br>\r\n&nbsp; &nbsp;      char c = 97;\n \n\n<br>\r\n&nbsp; &nbsp;       printf(\"%d, %d, %d\\n\", sizeof(i), sizeof(c), sizeof(c + i));\n \n\n<br>\r\n&nbsp; &nbsp;       return 0;\n\n\n<br>\r\n&nbsp; &nbsp;   }', '2,1,2', '2,2,8', '2,1,1', '2,1,4', 'D'),
(46, 'What will be the output of following program?: \n\n\n<br>\r\n&nbsp; &nbsp;#include&lt;stdio.h&gt;\n<br>\r\n&nbsp; &nbsp;\nint main()\n<br>\r\n&nbsp; &nbsp;\n{\n<br>\r\n&nbsp; &nbsp;\n    int a=0;\n<br>\r\n&nbsp; &nbsp;\n    a=a++ + a++ - a++ + ++a;\n<br>\r\n&nbsp; &nbsp;\n    printf(\"%d\\n\", a);\n<br>\r\n&nbsp; &nbsp;\n    return 0;\n<br>\r\n&nbsp; &nbsp;\n}', '2', '3', '5', '4', 'B'),
(49, 'what will be the output of following program?  \n\n<br>\r\n&nbsp; &nbsp; void fun(int **p)\n\n<br>\r\n&nbsp; &nbsp;\n{\n \n\n<br>\r\n&nbsp; &nbsp; static int q = 10;\n\n\n<br>\r\n&nbsp; &nbsp;  *p = &q;\n\n<br>\r\n&nbsp; &nbsp;\n}   \n\n<br>\r\n&nbsp; &nbsp; \n  \nint main()\n\n<br>\r\n&nbsp; &nbsp;\n{\n\n\n<br>\r\n&nbsp; &nbsp;  int r = 20;\n\n\n<br>\r\n&nbsp; &nbsp;  int *p = &r;\n\n\n<br>\r\n&nbsp; &nbsp;  fun(&p);\n \n\n<br>\r\n&nbsp; &nbsp; printf(\"%d\", *p);\n\n\n<br>\r\n&nbsp; &nbsp;  getchar();\n\n\n<br>\r\n&nbsp; &nbsp;  return 0;\n\n<br>\r\n&nbsp; &nbsp;\n} ', '20', '0', '10', 'error', 'C'),
(50, 'what will be the output of following program? <br>\r\n&nbsp; &nbsp; #include &lt;stdio.h&gt;\n<br>\r\n&nbsp; &nbsp;\nint main()\n\n<br>\r\n&nbsp; &nbsp;\n{\n\n\n<br>\r\n&nbsp; &nbsp;  int y = 10;\n    if (y++ &gt; 9 && y++ != 11 && y++ &gt; 11)\n\n<br>\r\n&nbsp; &nbsp;\n        printf(\"%d\", y);\n\n<br>\r\n&nbsp; &nbsp;\n    else\n\n\n<br>\r\n&nbsp; &nbsp;        printf(\"%d\", y);\n \n\n<br>\r\n&nbsp; &nbsp;   return 0;\n\n<br>\r\n&nbsp; &nbsp;\n}', '11', '12', '13', '14', 'B'),
(47, 'What will be the output of following program?  \n\n<br>\r\n&nbsp; &nbsp;#include&lt;stdio.h&gt;\n\n<br>\r\n&nbsp; &nbsp;\nint ar[] = {18, 23, 45, 56, 4, 6, 45};\n\n<br>\r\n&nbsp; &nbsp;\nint main()\n\n<br>\r\n&nbsp; &nbsp;\n{\n\n<br>\r\n&nbsp; &nbsp;\n    int i, x;\n\n<br>\r\n&nbsp; &nbsp;\n    x = (sizeof(ar)/sizeof(ar[0]));\n\n<br>\r\n&nbsp; &nbsp;\n\n    for (i=-1; i&lt;=(x-2); i++)\n\n<br>\r\n&nbsp; &nbsp;\n        printf(\"%d, \", ar[i+1]);\n\n<br>\r\n&nbsp; &nbsp;\n}', '23,45,40,33,22,4,6,55', '18,23,45,56,4,6,45', '12,23,45,67,39,89,80', '67,44,54,53,43,2,32', 'B'),
(45, 'What will be the output of following program? \n\n<br>\r\n&nbsp; &nbsp;\nInput: \n\n1 3\n\n\n<br>\r\n&nbsp; &nbsp;\n#include&lt;stdio.h&gt;\n\n\n<br>\r\n&nbsp; &nbsp;int main()\n\n<br>\r\n&nbsp; &nbsp;\n{\n \n\n<br>\r\n&nbsp; &nbsp;   int a, b;\n  <br>\r\n&nbsp; &nbsp;  if(scanf(\"%d%d\", &a, &b)==2)\n  <br>\r\n&nbsp; &nbsp;      printf(\"true\");\n\n<br>\r\n&nbsp; &nbsp;\n    else\n\n<br>\r\n&nbsp; &nbsp;\n        printf(\"false\");\n\n<br>\r\n&nbsp; &nbsp;\n    return 0;\n\n<br>\r\n&nbsp; &nbsp;\n}', 'True', 'False', 'depends on the compiler', 'error', 'A'),
(4, 'What will be the maximum size of a float variable?', '1bytes', '3bytes', '4bytes', '8 bytes', 'C'),
(57, 'What will be the final values of i and j in the following C code?\n\n  <br>\r\n&nbsp; &nbsp; #include &lt;stdio.h&gt;\n\n<br>\r\n&nbsp; &nbsp;\n    int x = 0;\n    int main()\n\n<br>\r\n&nbsp; &nbsp;\n{\n\n\n<br>\r\n&nbsp; &nbsp; int i = (f() + g()) | g(); //bitwise or\n\n<br>\r\n&nbsp; &nbsp;\n int j = g() | (f() + g()); //bitwise or\n\n<br>\r\n&nbsp; &nbsp;   }\n\n<br>\r\n&nbsp; &nbsp;\n    int f()<br>\r\n&nbsp; &nbsp;\n    {\n\n<br>\r\n&nbsp; &nbsp;\n        if (x == 0)\n\n<br>\r\n&nbsp; &nbsp;\n\n<br>\r\n&nbsp; &nbsp;\n            return x + 1;\n\n<br>\r\n&nbsp; &nbsp;\n        else\n\n<br>\r\n&nbsp; &nbsp;\n            return x - 1;\n\n<br>\r\n&nbsp; &nbsp;\n    }\n\n<br>\r\n&nbsp; &nbsp;\n    int g()\n\n<br>\r\n&nbsp; &nbsp;\n    {\n\n<br>\r\n&nbsp; &nbsp;\n        return x++;\n \n\n<br>\r\n&nbsp; &nbsp;   }', 'i value is 1 and j value is 1', 'i value is 0 and j value is 0', 'i value is 1 and j value is undefined', 'i and j value are undefined', 'C'),
(48, 'what will be output of following program? <br>\r\n&nbsp; &nbsp;  #include&lt;stdio.h&gt;\n <br>\r\n&nbsp;  &nbsp; union student\n\n\n<br>\r\n&nbsp; &nbsp;{\n    \n\n<br>\r\n&nbsp; &nbsp;int y[34];\n\n\n<br>\r\n&nbsp; &nbsp;    char var2[7];\n\n\n<br>\r\n&nbsp; &nbsp;    char arr[8];\n\n\n<br>\r\n&nbsp; &nbsp;    char ch[5];\n\n\n<br>\r\n&nbsp; &nbsp;};\n\n\n<br>\r\n&nbsp; &nbsp;int main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;    union student st;\n\n\n<br>\r\n&nbsp; &nbsp;    printf(\"%d\", sizeof(union student));\n\n\n<br>\r\n&nbsp; &nbsp;    return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', '136', '123', '143', '130', 'A'),
(42, 'What is the output? \n\n<br>\r\n&nbsp; &nbsp;#include &lt;stdio.h&gt;\n \n\n\n<br>\r\n&nbsp; &nbsp;struct sample {\n\n\n<br>\r\n&nbsp; &nbsp;    int a;\n\n\n<br>\r\n&nbsp; &nbsp;}\n\n<br>\r\n&nbsp; &nbsp; sample;\n \n\n\n<br>\r\n&nbsp; &nbsp;int main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;    sample.a = 100;\n\n\n<br>\r\n&nbsp; &nbsp;    printf(\"%d\", sample.a);\n\n\n<br>\r\n&nbsp; &nbsp;    return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', '0', '100', 'Error', 'Warning', 'B'),
(41, 'What is the output of this program? \n\n\n<br>\r\n&nbsp; &nbsp;#include &lt;stdio.h&gt;\n\n\n<br>\r\n&nbsp; &nbsp;int main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;    typedef struct tag \n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;        char str[10];\n\n\n<br>\r\n&nbsp; &nbsp;        int a;\n\n\n<br>\r\n&nbsp; &nbsp;    } \n\n<br>\r\n&nbsp; &nbsp;har;\n \n\n\n<br>\r\n&nbsp; &nbsp;    har h1, h2 = { \"IHelp\", 10 };\n\n\n<br>\r\n&nbsp; &nbsp;    h1 = h2;\n\n\n<br>\r\n&nbsp; &nbsp;    h1.str[1] = \'h\';\n\n\n<br>\r\n&nbsp; &nbsp;    printf(\"%s, %d\", h1.str, h1.a);\n\n\n<br>\r\n&nbsp; &nbsp;    return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', 'Error', ' IHelp, 10 ', ' IHelp, 0 ', ' Ihelp, 10 ', 'D'),
(64, 'What is the output of the following program?\n\n<br>\r\n&nbsp; &nbsp;#include&lt;stdio.h&gt;\n\n int main()\n<br>\r\n&nbsp; &nbsp;\n{ \n<br>\r\n&nbsp; &nbsp;\n   int a[3] = {2, ,1};\n<br>\r\n&nbsp; &nbsp;\n   \n   printf(\"%d\", a[a[0]]); \n<br>\r\n&nbsp; &nbsp;\n}', '0', '1', 'Compile error', '2', 'C'),
(63, 'What is the output of the following program?\n\n<br>\r\n&nbsp; &nbsp;#include&lt;stdio.h&gt;\n\n int main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;   int x = 65, *p = &x;\n\n\n<br>\r\n&nbsp; &nbsp;   \n   void *q=p;\n\n\n<br>\r\n&nbsp; &nbsp;   char *r=q;\n\n\n<br>\r\n&nbsp; &nbsp;   printf(\"%c\",*r);\n\n\n<br>\r\n&nbsp; &nbsp;}', 'A', '65', 'A - Garbage character.', 'D - Compile error', 'A'),
(68, 'What is the correct way of treating 9.81 as a long double?', '9.81L', '9.81LD', '9.81d', '9.81DL', 'A'),
(33, 'What is output of below program?\n\n\n\n<br>\r\n&nbsp; &nbsp;int main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;  int i;\n\n\n<br>\r\n&nbsp; &nbsp;  for(i=0; i&lt;5; i++);\n\n\n<br>\r\n&nbsp; &nbsp;  {\n\n\n<br>\r\n&nbsp; &nbsp;    printf(\"cppbuzz\");\n  }\n\n\n\n<br>\r\n&nbsp; &nbsp;  return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', 'cppbuzz is printed 5 times', 'Compilation Error', 'cppbuzz is printed 1 time', 'Nothing is printed', 'C'),
(40, 'How many times cppbuzz will be printed?\n\n\n<br>\r\n&nbsp; &nbsp;\nint main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;  int i;\n\n\n<br>\r\n&nbsp; &nbsp;  for(i=1; i&lt;5; i++)\n\n\n<br>\r\n&nbsp; &nbsp;      printf(\"cppbuzz\");\n\n\n<br>\r\n&nbsp; &nbsp;return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', '4', '6', '8', '12', 'A'),
(13, 'What is meant by a in the following C operation?fp = fopen(\"Random.txt\", \"a\")', 'Attach', 'Append', 'Apprehend', 'Add', 'B'),
(8, 'What is a lint?', ' C compiler', 'Interactive debugger', 'Analyzing tool', 'C interpreter', 'C'),
(11, 'What is #include &lt;stdio.h&gt;', 'Preprocessor directive', 'Inclusion directive', 'File inclusion directive', 'None of the mentioned', 'A'),
(12, 'The C-preprocessors are specified with ___ symbol', '$', '#', '\"\"', '&', 'B'),
(5, 'The bitwise AND operator is used for', 'Masking', 'Division', 'Division', 'Shifting bits', 'A'),
(66, 'Predict the output of the following code segment:\n\n\n<br>\r\n&nbsp; &nbsp;// Add stdio.h header file in below code\n\n\n\n<br>\r\n&nbsp; &nbsp;int main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;int array[10] = {3, 0, 8, 1, 12, 8, 9, 2, 13, 10};\n\n\n<br>\r\n&nbsp; &nbsp;int x, y, z;\n\n\n<br>\r\n&nbsp; &nbsp;x = ++array[2];\n\n\n<br>\r\n&nbsp; &nbsp;y = array[2]++;\n\n\n<br>\r\n&nbsp; &nbsp;z = array[x++];\n\n\n<br>\r\n&nbsp; &nbsp;printf(\"%d %d %d, x, y, z\");\n\n\n<br>\r\n&nbsp; &nbsp;return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', '10 9 10', '9 9 10', '9 10 9', 'None of the above', 'A'),
(44, 'Predict the output of below programs.\n\n\n\n\n\n<br>\r\n&nbsp; &nbsp;int fun(char *str1)\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;  char *str2 = str1;\n\n\n<br>\r\n&nbsp; &nbsp;  while(*++str1);\n\n\n<br>\r\n&nbsp; &nbsp;  return (str1-str2);\n\n\n<br>\r\n&nbsp; &nbsp;}    \n  \n\n\n<br>\r\n&nbsp; &nbsp;int main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;  char *str = \"usharama\";\n\n\n<br>\r\n&nbsp; &nbsp;  printf(\"%d\", fun(str));\n\n\n<br>\r\n&nbsp; &nbsp;  getchar();\n\n\n<br>\r\n&nbsp; &nbsp;  return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', '12', '11', '8', '9', 'C'),
(34, 'What will be the output of the following C code?\n\n <br>\r\n&nbsp; &nbsp;   int main()\n\n\n<br>\r\n&nbsp; &nbsp;{ \n\n\n<br>\r\n&nbsp; &nbsp;    int a = printf (\"CppBuzz.com\");\n\n\n<br>\r\n&nbsp; &nbsp;    printf(\"%d\", a);\n\n\n<br>\r\n&nbsp; &nbsp;    return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', 'compilation error', '0', 'CppBuzz.com', 'CppBuzz.com11', 'D'),
(36, 'What will be the output of the following C code?\n\n <br>\r\n&nbsp; &nbsp;   int main()\n<br>\r\n&nbsp; &nbsp;\n{\n<br>\r\n&nbsp; &nbsp;\n int  _ = 10;\n\n\n<br>\r\n&nbsp; &nbsp; int  __ = 20;\n\n\n<br>\r\n&nbsp; &nbsp; int  ___ = _ + __;\n\n\n<br>\r\n&nbsp; &nbsp; printf(\"__%d\",___);\n\n\n<br>\r\n&nbsp; &nbsp; return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}\n\n', 'Compilation Error', 'Run time error', '__0', '__30', 'D'),
(38, 'What will be the output of the following C code?\n\n <br>\r\n&nbsp; &nbsp;   int main()\n<br>\r\n&nbsp; &nbsp;\n{\n\n\n<br>\r\n&nbsp; &nbsp;    int a = 320;\n\n\n<br>\r\n&nbsp; &nbsp;    char *ptr;\n\n\n<br>\r\n&nbsp; &nbsp;    ptr =( char *)&a;\n\n\n<br>\r\n&nbsp; &nbsp;    printf(\"%d\",*ptr);\n\n\n<br>\r\n&nbsp; &nbsp;    return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', '320', '60', '160', '64', 'D'),
(37, 'What will be the output of the following C code?\n\n <br>\r\n&nbsp; &nbsp;   int main()\n\n\n<br>\r\n&nbsp; &nbsp;{\n\n\n<br>\r\n&nbsp; &nbsp;    char arr[5]=\"The CppBuzz.com\";\n\n\n<br>\r\n&nbsp; &nbsp;    printf(\"%s\",arr);\n\n\n<br>\r\n&nbsp; &nbsp;   return 0;\n\n\n<br>\r\n&nbsp; &nbsp;}', 'Compilation Error','The CppBuzz', 'The CppBuzz.com', 'The C', 'A'),
(24, 'If the size of the array is less than the number of initializers then,', 'Extra values are being ignored ', 'Generates an error message', 'Size of Array is increased', 'Size is neglected when values are given', 'A'),
(31, 'If addition had higher precedence than multiplication, then the value of the expression (1 + 2 * 3 + 4 * 5) would be which of the following?', '27', '47', '69', '105', 'D'),
(14, 'How many times will the following loop execute? <br>\r\n&nbsp; &nbsp;  for(j = 1; j &lt;= 10; j = j-1)', 'Forever', 'Never', '0', '1', 'A'),
(61, 'How many times will TechnoQuiz be printed in the above program? <br>\r\n&nbsp; &nbsp;  #include &lt;stdio.h&gt;\n<br>\r\n&nbsp; &nbsp;\n int main()\n<br>\r\n&nbsp; &nbsp;\n{\n<br>\r\n&nbsp; &nbsp;\n    int i = 1024;\n<br>\r\n&nbsp; &nbsp;\n    for (; i; i &gt;&gt;= 1)\n<br>\r\n&nbsp; &nbsp;\n        printf(\"TechnoQuiz\");\n<br>\r\n&nbsp; &nbsp;\n    return 0;\n<br>\r\n&nbsp; &nbsp;\n}', '10', '11', 'infinite', 'The program will show compile-time error', 'B'),
(62, 'How many times TechnothonQuiz is printed in the above program ?   <br>\r\n&nbsp; &nbsp;              #include &lt;stdio.h&gt;\n <br>\r\n&nbsp; &nbsp;\n#define PRINT(i, limit)<br>\r\n&nbsp; &nbsp;int main()<br>\r\n&nbsp; &nbsp;{<br>\r\n&nbsp; &nbsp;int i,limit;<br>\r\n&nbsp; &nbsp; do \n <br>\r\n&nbsp; &nbsp;\n { \n <br>\r\n&nbsp; &nbsp;\n  if (i++ &lt; limit) \n <br>\r\n&nbsp; &nbsp;\n  { \n <br>\r\n&nbsp; &nbsp;\n printf(\"TechnothonQuiz\"); \n\n<br>\r\n&nbsp; &nbsp;\n  continue; \n\n<br>\r\n&nbsp; &nbsp;\n } \n\n<br>\r\n&nbsp; &nbsp;\n }<br>\r\n&nbsp; &nbsp;while(0);\n \n\n<br>\r\n&nbsp; &nbsp;\nint main()\n\n<br>\r\n&nbsp; &nbsp;\n{\n\n<br>\r\n&nbsp; &nbsp;\n    int i = 0;\n<br>\r\n&nbsp; &nbsp;    PRINT(i, 3);<br>\r\n&nbsp; &nbsp;}\n\n<br>\r\n&nbsp; &nbsp;\n    return 0;\n\n<br>\r\n&nbsp; &nbsp;\n}  ', '1', '3', '4', 'compile-time error', 'A'),
(18, 'How many number of pointer (*) does C have against a pointer variable declaration?', '7', '127', '255', 'No limits', 'D'),
(60, 'Comment on the following declaration.\n<br>\r\n&nbsp; &nbsp;\n    int (*ptr)(); // i)\n    char *ptr[]; // ii)', ' Both i) and ii) and cannot exist due to same name', 'i) is legal, ii) is illegal', ' i) is illegal, ii) is legal', 'Both i) and ii) will work legal and flawlessly', 'A'),
(65, 'Choose the invalid predefined macro as per ANSI C.', '__FILE__', ' __DATE__', '__TIME__', '__C++__', 'D'),
(2, 'Who is the father of father of C language. <br>', 'Dennis MacAlistair Ritchie', 'Dennis Ritchie', 'Alistair E. Ritchie', 'Stuart Ritchie', 'C'),
(23, 'A Link is', 'a compiler', ' an active debugger', 'a C interpreter ', 'an analyzing tool in C', 'D'),
(32, 'Which of the following SLT template class is a container adaptor class?', 'Stack', 'List', 'Deque', 'Vector', 'A'),
(3, 'Which of the following is a Scalar Data type', 'Float', 'Array', 'Union', 'Pointers', 'A'),
(21, 'In C language, FILE is of which data type?', 'int', 'char*', 'struct', 'None of the mentioned', 'A'),
(55, '. What will be the output of the following C code snippet?\n\n<br>\r\n&nbsp; &nbsp;#include &lt;stdio.h&gt;\n\n\n<br>\r\n&nbsp; &nbsp;    void main()\n\n\n<br>\r\n&nbsp; &nbsp;    {\n\n\n<br>\r\n&nbsp; &nbsp;        1 &lt; 2 ? return 1: return 2;\n\n\n<br>\r\n&nbsp; &nbsp;    }', 'returns1', 'returns 2', 'varies', 'Compile time error', 'D'),
(51, ' What will be the output of the following C function?\n\n <br>\r\n&nbsp; &nbsp;   #include &lt;stdio.h&gt;\n <br>\r\n&nbsp; &nbsp;\n    enum birds {SPARROW, PEACOCK, PARROT};\n \n\n<br>\r\n&nbsp; &nbsp;   enum animals {TIGER = 8, LION, RABBIT, ZEBRA};\n\n\n<br>\r\n&nbsp; &nbsp;    int main()\n \n\n<br>\r\n&nbsp; &nbsp;   {\n\n\n<br>\r\n&nbsp; &nbsp;        enum birds m = TIGER;\n \n\n<br>\r\n&nbsp; &nbsp;       int k;\n\n\n<br>\r\n&nbsp; &nbsp;        k = m;\n\n\n<br>\r\n&nbsp; &nbsp;        printf(\"%d\\n\", k);\n\n\n<br>\r\n&nbsp; &nbsp;        return 0;\n\n\n<br>\r\n&nbsp; &nbsp;    }', '0', '1', '8', 'Compile time error', 'C'),
(59, ' What will be the output of the following C code?\n\n <br>\r\n&nbsp; &nbsp;   #include &lt;stdio.h&gt;\n \n\n<br>\r\n&nbsp; &nbsp;   void f(int a[][3])\n    \n\n<br>\r\n&nbsp; &nbsp;{\n    \n\n<br>\r\n&nbsp; &nbsp;    a[0][1] = 3;\n   \n\n<br>\r\n&nbsp; &nbsp;     int i = 0, j = 0;\n   \n\n<br>\r\n&nbsp; &nbsp;     for (i = 0; i &lt; 2; i++)\n \n\n<br>\r\n&nbsp; &nbsp;       for (j = 0; j &lt; 3; j++)\n   \n\n<br>\r\n&nbsp; &nbsp;     printf(\"%d\", a[i][j]);\n\n\n<br>\r\n&nbsp; &nbsp;    }\n   \n\n<br>\r\n&nbsp; &nbsp; void main()\n\n\n<br>\r\n&nbsp; &nbsp;    {\n  \n\n<br>\r\n&nbsp; &nbsp;      int a[2][3] = {0};\n  \n\n<br>\r\n&nbsp; &nbsp;      f(a);\n \n\n<br>\r\n&nbsp; &nbsp;   }', '030000', 'Junk 3 junk junk junk junk', 'Compile time error', 'All junk values', 'A'),
(58, ' What is the output of this C code?\n\n  <br>\r\n&nbsp; &nbsp; #include &lt;stdio.h&gt;\n\n\n<br>\r\n&nbsp; &nbsp;  int  main()\n   \n\n<br>\r\n&nbsp; &nbsp;{\n   \n\n<br>\r\n&nbsp; &nbsp;    if (sizeof(int) &gt; -1)\n\n\n<br>\r\n&nbsp; &nbsp;           printf(\"True\");\n\n\n<br>\r\n&nbsp; &nbsp;       else\n\n\n<br>\r\n&nbsp; &nbsp;           printf(\"False\");\n\n\n<br>\r\n&nbsp; &nbsp;   }', 'True', 'error', 'False', 'None of the mentioned', 'C'),
(39, ' what is the output of the program?  <br>\r\n&nbsp; &nbsp;    int main()\n\n<br>\r\n&nbsp; &nbsp;\n{  \n\n<br>\r\n&nbsp; &nbsp;  int x;\n \n\n<br>\r\n&nbsp; &nbsp;   x=10,20,30;\n   \n\n<br>\r\n&nbsp; &nbsp; printf(\"%d\",x);\n\n\n<br>\r\n&nbsp; &nbsp;    return 0;\n\n<br>\r\n&nbsp; &nbsp;\n}', '10', '20', '30', '10,20,30', 'A'),
(25, ' What is the 16-bit compiler allowable range for integer constants?', ' -3.4e38 to 3.4e38', ' -32767 to 32768', ' -32668 to 32667', ' -32768 to 32767', 'D'),
(7, ' What is short int in C programming?', 'The basic data type of C', 'Qualifier', 'Short is the qualifier and int is the basic data type', 'All of the mentioned', 'C'),
(43, ' what is output of this program? \n\n\n\n<br>\r\n&nbsp; &nbsp;<br>\r\n&nbsp; &nbsp;#include &lt;stdio.h&gt;\n\n\n<br>\r\n&nbsp; &nbsp;int main()\n\n<br>\r\n&nbsp; &nbsp;\n{\n   \n\n<br>\r\n&nbsp; &nbsp; union test \n\n<br>\r\n&nbsp; &nbsp;{\n \n\n<br>\r\n&nbsp; &nbsp;       int i;\n     \n\n<br>\r\n&nbsp; &nbsp;   int j;\n  \n\n<br>\r\n&nbsp; &nbsp;  };\n \n\n\n<br>\r\n&nbsp; &nbsp;    union test var = 10;\n \n\n<br>\r\n&nbsp; &nbsp;   printf(\"%d, %d\\n\", var.i, var.j);\n\n<br>\r\n&nbsp; &nbsp;\n}', '10,10', '10,0', '0,10', 'Compile Error', 'D'),
(30, ' What does this statement mean?\n\n\n\n<br>\r\n&nbsp; &nbsp;x - = y + 1;  ', 'x = x - y + 1', ' x = -x - y - 1', 'x = x + y - 1', ' x = x - y - 1', 'D'),
(29, ' Study the following array definition\n\n\n\n<br>\r\n&nbsp; &nbsp;int num[10] = {3, 3, 3};\n\n<br>\r\n&nbsp; &nbsp;  \nWhich of the following statement is correct?', 'num[9] is the last element of the array num', 'The value of num[8] is 3', 'The value of num[3] is 3', 'None of the mentioned', 'A');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */
